### ISSUE TITLE
Make this repo private! 

### ISSUE THREAD

**Issue by jeremiahlukus** [ThomasConnolly/paul#10]
You really need to do this especially since you posted this repo on reddit. There are a few security concerns. It’s free to make the repo private. If you need help message back!

**Comment by et** [comment]
I’ve reported this repo to Github as the author seems to not heeding the advice that many have already pointed out: https://reddit.app.link/09hKJ6o7e3

**Comment by mlh758** [comment]
@ThomasConnolly just deleting the files and committing that delete doesn't remove them, they're still available in the repo's git history.

**Comment by jeremiahlukus** [comment]
https://github.com/ThomasConnolly/paul/blob/5c4fbd60e34ed462ab877cdf7544493c171b0a86/member.csv

**Comment by jeremiahlukus** [comment]
Please fix this before something bad happens
